apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: qbshop
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: qbs-migration
        image: 9836sagar9836/qbshop-migration:22
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
